version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fra-awsomeblog-back-stk"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a7bqfmc1rzl"
s3_prefix = "fra-awsomeblog-back-stk"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "pTenantName=\"AWSomeTV\" pProjectName=\"prjAWSomeBlog\" pCallbackURL=\"http://localhost:4200/login,https://www.francas.team/login\" pLogoutURL=\"http://localhost:4200/home,https://www.francas.team/home\" pAdminEmail=\"mcfranca@amazon.com\" pTenantId=\"1\""
